Host key verification failed.
1

PLAY [gz-hadoop-worker] ********************************************************

TASK [Gathering Facts] *********************************************************
ok: [hadoop-0004]
ok: [hadoop-0005]
ok: [hadoop-0002]
ok: [hadoop-0003]
ok: [hadoop-0001]
ok: [hadoop-0007]
ok: [hadoop-0006]
ok: [hadoop-0008]
ok: [hadoop-0009]
ok: [hadoop-0010]
ok: [hadoop-0011]
ok: [hadoop-0013]
ok: [hadoop-0015]
ok: [hadoop-0016]
ok: [hadoop-0017]
ok: [hadoop-0014]
ok: [hadoop-0018]
ok: [hadoop-0022]
ok: [hadoop-0021]
ok: [hadoop-0019]
ok: [hadoop-0020]
ok: [hadoop-0023]
ok: [hadoop-0012]
ok: [hadoop-0024]
fatal: [hadoop-0027]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host hadoop-0027 port 22: No route to host\r\n", "unreachable": true}
ok: [hadoop-0026]
ok: [hadoop-0029]
ok: [hadoop-0028]
ok: [hadoop-0031]
ok: [hadoop-0030]
ok: [hadoop-0033]
ok: [hadoop-0025]
ok: [hadoop-0032]
ok: [hadoop-0034]
ok: [hadoop-0037]
ok: [hadoop-0038]
ok: [hadoop-0035]
ok: [hadoop-0036]
ok: [hadoop-0039]
ok: [hadoop-0042]
ok: [hadoop-0044]
ok: [hadoop-0040]
ok: [hadoop-0043]
ok: [hadoop-0041]
ok: [hadoop-0045]
ok: [hadoop-0046]
ok: [hadoop-0049]
ok: [hadoop-0048]
ok: [hadoop-0047]
ok: [hadoop-0050]
ok: [hadoop-0051]
ok: [hadoop-0053]
ok: [hadoop-0052]

TASK [copy model to hadoop cluster] ********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0001]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0002]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0003]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0004]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0005]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0006]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0007]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0008]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0009]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0010]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0011]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0012]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0013]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0014]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0015]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0016]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0017]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0018]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0019]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0020]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0021]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0022]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0023]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0024]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0025]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0026]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0028]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0029]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0030]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0031]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0032]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0033]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0034]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0035]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0036]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0037]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0038]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0039]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0040]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0041]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0042]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0043]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0044]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0045]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0046]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0047]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0048]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0049]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0050]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0051]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0052]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [hadoop-0053]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/retinamask20190521' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP *********************************************************************
hadoop-0001                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0002                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0003                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0004                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0005                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0006                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0007                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0008                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0009                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0010                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0011                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0012                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0013                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0014                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0015                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0016                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0017                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0018                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0019                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0020                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0021                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0022                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0023                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0024                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0025                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0026                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0027                : ok=0    changed=0    unreachable=1    failed=0   
hadoop-0028                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0029                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0030                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0031                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0032                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0033                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0034                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0035                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0036                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0037                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0038                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0039                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0040                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0041                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0042                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0043                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0044                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0045                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0046                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0047                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0048                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0049                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0050                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0051                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0052                : ok=1    changed=0    unreachable=0    failed=1   
hadoop-0053                : ok=1    changed=0    unreachable=0    failed=1   

4
[Finish] Success to check [retinamask20190521]