Traceback (most recent call last):
  File "check_automap_ver_v2.py", line 86, in <module>
    main()
  File "check_automap_ver_v2.py", line 79, in main
    app_id = sys.argv[1]
IndexError: list index out of range
[Finish] Failed to check []